### ISSUE TITLE
Add a git submodule to json_spirit

### ISSUE THREAD

**Issue by WilliamTambellini** [highperformancecoder/minsky#297]
Hello Russell
Would you consider adding a git submodule to a json_spirit repo for easier compilation of minsky ?
Using 
https://github.com/highperformancecoder/json_spirit
would moreover assure using the right fork/branch/version.
From compiling.md:
```
* json_spirit can also be built from [sources](hhttps://github.com/highperformancecoder/json_spirit) instead of adding the opensuse build service as a repository. 
* Other github clones of json_spirit also exist, but the highperformancecoder version has some modifications needed for Minsky, which have been pull requested upstream. Note that most recent json_spirits do not build mValues by default, so you need to configure that option with cmake.
```
Kind

**Comment by highperformancecoder** [comment]
Well, yes - the minsky repository already has a number of other submodules: ecolab, exprtk, RavelCAPI and certify. What's one more? I did consider it, but decided against because json_spirit is cmake-based. Ideally, the necessary changes should be integrated upstream, but json_spirit is unfortunately not that well managed. 

In the words of Fagan, "I think I'd better think it out again!"

**Comment by WilliamTambellini** [comment]
Hum, have you tried using the "header only" imp of json_spirit :
https://github.com/highperformancecoder/json_spirit/tree/master/json_headers_only_demo

**Comment by highperformancecoder** [comment]
Oh, OK - that is another possibility. I guess that mode wasn't
documented in the original json_spirit documentation, but perhaps
json_spirit can be added as a submodule to classdesc, and do it all as
header only.


On Sat, Nov 13, 2021 at 05:51:51PM -0800, William Tambellini wrote:
> Hum, have you tried using the "header only" imp of json_spirit :
> https://github.com/highperformancecoder/json_spirit/tree/master/
> json_headers_only_demo
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. *
> 

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     ***@***.***
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Thanks for this suggestion. I have added json_spirit as a submodule to classdesc, which in turn is a submodule of ecolab, which is in turn a submodule of minsky. It is integrated in the RESTService branch. I'll probably leave that for now, since it will be likely to be integrated within the next couple of months, rather than risk adding more merge pain, as master branch does not depend on my local json_spirit changes yet.
