### ISSUE TITLE
No .desktop file in Fedora package

### ISSUE THREAD

**Issue by aledomu** [highperformancecoder/minsky#330]
If I knew what icon to use and how to integrate it in the build process I could send a PR.

Edit: I recommend that the icon and desktop files use the reverse-DNS notation just for keeping up with the modern Linux desktop conventions. Flatpak packages require it is set up that way.

**Comment by highperformancecoder** [comment]
The icon can be found in gui-tk/icons/MinskyLogo.svg. Derived icon files .ico and .icns can be found in gui-js/apps/minsky-electron/src/assets.

**Comment by highperformancecoder** [comment]
The build process can be found in https://build.opensuse.org/package/show/home:hpcoder1/minsky-restservice and https://build.opensuse.org/package/show/home:hpcoder1/minsky. For fedora, the minsky.spec file controls to build.

Since Minsky 3, there are two interlinked projects - minsky-restservice is the C++ backend, and is a conventional Makefile project that builds a "node addon" - essentially a dynamic library exposing a node friendly API., and minsky, which contains the packaged Javascript built from Typescript source code. I commit the built files to the OBS project, because there didn't seem any way to run npm on the OBS build farm (firewalls get in the way). Fortunately it is distribution agnostic, but architecture specific ( x86_64 only, I'm afraid).

That said, the desktop files probably need to be located where the electron builder and packager  can find them. I haven't delved into the manuals, so I don't know where they would be. The command to generate a linux package is "npm run export:package:linux" in  the gui-js directory.

Note - there is a [ticket already open for this issue](https://sourceforge.net/p/minsky/features/179/). Feel free to take ownership of that ticket. Note, also we're not using the Github issues system, mostly for historical continuity reasons rather than there being anything wrong with it. Also, I don't personally use either Gnome or KDE, so I would need to do a lot of reading up on those window managers to understand how to configure the desktop files.

**Comment by highperformancecoder** [comment]
Closing this as a duplicate.
