### ISSUE TITLE
Where is log file

### ISSUE THREAD

**Issue by martinfreedman** [highperformancecoder/minsky#48]
Running latest release on windows 10. Cannot see any version number in the GUI. Have numerous crashes and freezes but cannot find any log file apart from in event viewer saying application has hung.

**Comment by highperformancecoder** [comment]
On Thu, Apr 06, 2017 at 08:20:51AM -0700, martinfreedman wrote:
> Running latest release on windows 10. Cannot see any version number in the GUI. Have numerous crashes and freezes but cannot find any log file apart from in event viewer saying application has hung.
> 

The version number is available in the "About Minsky" box.

There is no log file as such. On systems other than Windows, error
messages are written to the console. On windows, the act of writing a
message to the console causes the application to crash!

Could you please describe in detail what you were doing to cause the
crash, and I'll try to repro the problem here. Video screen capture
programs have proved useful in the past to see exactly what the issue
is.

Cheers

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by highperformancecoder** [comment]
Nothing to do here...
